# Docker Compose file for ckan development
# ------------------------------------------------
# The purpose of this docker-compose file is to simplify setting up a
# development environment for CKAN. It defines Docker based
# services for all external CKAN dependencies (DB, Solr, Redis) but not for
# CKAN itself - you should probably run CKAN in a local virtual environment
# to simplify debugging.

version: "3"

volumes:
  db_data:

services:
  db:
    image: ckan/ckan-postgres-dev:master
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  solr:
    image: ckan/ckan-solr-dev:master
    ports:
      - 8983:8983
  redis:
    image: redis:latest
    ports:
      - 6379:6379
